# Generated by Django 3.0.8 on 2020-07-14 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AdrListe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brukerliste.Adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Bruker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornavn', models.CharField(max_length=200)),
                ('etternavn', models.CharField(max_length=200)),
                ('epost', models.EmailField(max_length=250, unique=True)),
                ('broyting', models.BooleanField()),
                ('faktureres', models.BooleanField()),
                ('notat', models.TextField()),
                ('adr', models.ManyToManyField(through='brukerliste.AdrListe', to='brukerliste.Adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.DateField(auto_now=True)),
                ('bruker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brukerliste.Bruker')),
            ],
        ),
        migrations.CreateModel(
            name='Poststed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postnr', models.CharField(max_length=4)),
                ('poststed', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis_pris', models.IntegerField()),
                ('vinter_pris', models.IntegerField()),
                ('aar', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telefonnr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name='TlfListe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bruker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brukerliste.Bruker')),
                ('tlf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brukerliste.Telefonnr')),
            ],
        ),
        migrations.CreateModel(
            name='Hytte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gnr', models.CharField(max_length=4)),
                ('bnr', models.CharField(max_length=4)),
                ('sone', models.CharField(choices=[('Nedre', 'Nedre'), ('Øvre', 'Øvre')], max_length=8)),
                ('eier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='brukerliste.Bruker')),
            ],
            options={
                'unique_together': {('gnr', 'bnr')},
            },
        ),
        migrations.CreateModel(
            name='FakturaLinje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faktura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brukerliste.Faktura')),
                ('hytte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brukerliste.Hytte')),
                ('pris', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brukerliste.Pris')),
            ],
        ),
        migrations.AddField(
            model_name='faktura',
            name='hytter',
            field=models.ManyToManyField(through='brukerliste.FakturaLinje', to='brukerliste.Hytte'),
        ),
        migrations.AddField(
            model_name='bruker',
            name='tlf',
            field=models.ManyToManyField(through='brukerliste.TlfListe', to='brukerliste.Telefonnr'),
        ),
        migrations.AddField(
            model_name='adrliste',
            name='bruker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brukerliste.Bruker'),
        ),
        migrations.AddField(
            model_name='adresse',
            name='postnr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brukerliste.Poststed'),
        ),
    ]
