# Generated by Django 3.0.8 on 2020-08-10 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bruker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornavn', models.CharField(max_length=200)),
                ('etternavn', models.CharField(max_length=200)),
                ('epost', models.EmailField(blank=True, max_length=250, null=True)),
                ('broyting', models.BooleanField()),
                ('faktureres', models.BooleanField()),
                ('notat', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hytte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gnr', models.CharField(max_length=4)),
                ('bnr', models.CharField(max_length=4)),
                ('sone', models.CharField(choices=[('Nedre', 'Nedre'), ('Øvre', 'Øvre')], max_length=8)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('eier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hytte', to='brukerliste.Bruker')),
            ],
            options={
                'unique_together': {('gnr', 'bnr')},
            },
        ),
        migrations.CreateModel(
            name='Poststed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postnr', models.CharField(max_length=4, unique=True)),
                ('poststed', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TidligereEier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overdratt', models.DateField()),
                ('gammel_eier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gammel_eier', to='brukerliste.Bruker')),
                ('hytte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tidligere_eier', to='brukerliste.Hytte')),
                ('ny_eier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ny_eier', to='brukerliste.Bruker')),
            ],
        ),
        migrations.CreateModel(
            name='Telefonnr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.CharField(max_length=15, unique=True)),
                ('bruker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tlf', to='brukerliste.Bruker')),
            ],
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate', models.CharField(max_length=250)),
                ('bruker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresse', to='brukerliste.Bruker')),
                ('postnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brukerliste.Poststed')),
            ],
        ),
    ]
