# Generated by Django 3.0.8 on 2020-07-14 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brukerliste', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlfliste',
            name='bruker',
        ),
        migrations.RemoveField(
            model_name='tlfliste',
            name='tlf',
        ),
        migrations.RemoveField(
            model_name='bruker',
            name='adr',
        ),
        migrations.RemoveField(
            model_name='bruker',
            name='tlf',
        ),
        migrations.AddField(
            model_name='adresse',
            name='bruker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brukerliste.Bruker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telefonnr',
            name='bruker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='brukerliste.Bruker'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AdrListe',
        ),
        migrations.DeleteModel(
            name='TlfListe',
        ),
    ]
