# Generated by Django 3.0.8 on 2020-08-10 15:10

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brukerliste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referanse', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('faktura_dato', models.DateField(auto_now_add=True)),
                ('oppdatert_dato', models.DateTimeField(auto_now=True)),
                ('betalt', models.BooleanField(default=False)),
                ('sendt', models.BooleanField(default=False)),
                ('bruker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faktura', to='brukerliste.Bruker')),
            ],
        ),
        migrations.CreateModel(
            name='Pris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('basis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ovre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('broyting', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beskrivelse_annet', models.CharField(blank=True, max_length=250, null=True)),
                ('annet', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FakturaLinje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittel', models.CharField(max_length=250)),
                ('pris', models.DecimalField(decimal_places=2, max_digits=10)),
                ('faktura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fakturalinje', to='invoicing.Faktura')),
                ('hytte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flinje', to='brukerliste.Hytte')),
            ],
        ),
    ]
