# Generated by Django 3.0.8 on 2020-08-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pris',
            name='beskjed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
